In [1]:
import re
import string
from pyvi import ViTokenizer, ViPosTagger, ViUtils
import csv
from collections import Counter


class Preprocess:
    def __init__(self):
        stop_word = []
        with open('stopword.txt') as fp:
            for row in fp:
                stop_word.append(row.strip())
        stop_word = set(stop_word)
        self.stop_word = stop_word
        return
    @staticmethod
    def readStopWord(self):
        stop_word = []
        with open('stopword.txt') as fp:
            for row in fp:
                stop_word.append(row.strip())
        stop_word = set(stop_word)
        
        return stop_word

    def replaceCompositUnicode(self, str):
        str = str.replace('à', 'à')
        str = str.replace('ả', 'ả')
        str = str.replace('ã', 'ã')
        str = str.replace('á', 'á')
        str = str.replace('ạ', 'ạ')
        str = str.replace('ấ', 'ấ')
        str = str.replace('ầ', 'ầ')
        str = str.replace('ậ', 'ậ')
        str = str.replace('ẩ', 'ẩ')
        str = str.replace('ẫ', 'ẫ')
        str = str.replace('ắ', 'ắ')
        str = str.replace('ằ', 'ằ')
        str = str.replace('ặ', 'ặ')
        str = str.replace('ẳ', 'ẳ')
        str = str.replace('ẵ', 'ẵ')
        str = str.replace('è', 'è')
        str = str.replace('ẻ', 'ẻ')
        str = str.replace('ẽ', 'ẽ')
        str = str.replace('é', 'é')
        str = str.replace('ẹ', 'ẹ')
        str = str.replace('ế', 'ế')
        str = str.replace('ề', 'ề')
        str = str.replace('ệ', 'ệ')
        str = str.replace('ể', 'ể')
        str = str.replace('ễ', 'ễ')
        str = str.replace('ì', 'ì')
        str = str.replace('ỉ', 'ỉ')
        str = str.replace('ĩ', 'ĩ')
        str = str.replace('í', 'í')
        str = str.replace('ị', 'ị')
        str = str.replace('ò', 'ò')
        str = str.replace('ỏ', 'ỏ')
        str = str.replace('õ', 'õ')
        str = str.replace('ó', 'ó')
        str = str.replace('ọ', 'ọ')
        str = str.replace('ố', 'ố')
        str = str.replace('ồ', 'ồ')
        str = str.replace('ộ', 'ộ')
        str = str.replace('ổ', 'ổ')
        str = str.replace('ỗ', 'ỗ')
        str = str.replace('ớ', 'ớ')
        str = str.replace('ờ', 'ờ')
        str = str.replace('ợ', 'ợ')
        str = str.replace('ở', 'ở')
        str = str.replace('ỡ', 'ỡ')
        str = str.replace('ù', 'ù')
        str = str.replace('ủ', 'ủ')
        str = str.replace('ũ', 'ũ')
        str = str.replace('ú', 'ú')
        str = str.replace('ụ', 'ụ')
        str = str.replace('ứ', 'ứ')
        str = str.replace('ừ', 'ừ')
        str = str.replace('ự', 'ự')
        str = str.replace('ử', 'ử')
        str = str.replace('ữ', 'ữ')
        str = str.replace('ỳ', 'ỳ')
        str = str.replace('ỷ', 'ỷ')
        str = str.replace('ỹ', 'ỹ')
        str = str.replace('ý', 'ý')
        str = str.replace('ỵ', 'ỵ')
        return str

    def removeSpecialCharacter(self, str):
        # Loai bo ki tu dac biet
        str = re.sub(r'[^0-9a-zăâđêôơưàảãáạấầậẩẫắằặẳẵèẻẽéẹếềệểễìỉĩíịòỏõóọốồộổỗớờợởỡùủũúụứừựửữỳỷỹýỵ,\s\*]+', ' ',str)
        # Xoa bo khoang trang dai
        str = re.sub(' {2,}', ' ', str)
        return str

    def replaceAcronym(self, str):
        # mot so tu viet tat
        # 1*->1 sao, 2*-> 2 sao,...
        str = re.sub('(^| )([0-9])\*($| )', r'\1sao\2', str)
        # 1sao -> 1 sao, 2sao -> 2 sao, ...
        str = re.sub('(^| )([0-9])sao($| )', r'\1sao\2', str)
        # * -> sao
        str = re.sub("(^| )\*($| )", r"\1sao\2", str)
        # s -> sao
        str = re.sub("(^| )s($| )", r"\1sao\2", str)
        str = re.sub("(^| )sp($| )", r"\1sản phẩm\2", str)
        str = re.sub("(^| )rat($| )", r"\1rất\2", str)
        str = re.sub("(^| )dang($| )", r"\1đáng\2", str)
        str = re.sub("(^| )nhiu($| )", r"\1nhiều\2", str)
        str = re.sub("(^| )nhìu($| )", r"\1nhiều\2", str)
        str = re.sub("(^| )nhieu($| )", r"\1nhiều\2", str)
        str = re.sub("(^| )tot($| )", r"\1tốt\2", str)
        str = re.sub("(^| )tôt($| )", r"\1tốt\2", str)
        str = re.sub("(^| )muot($| )", r"\1mượt\2", str)
        str = re.sub("(^| )muọt($| )", r"\1mượt\2", str)
        str = re.sub("(^| )mươt($| )", r"\1mượt\2", str)
        str = re.sub("(^| )may($| )", r"\1máy\2", str)
        str = re.sub("(^| )tr($| )", r"\1trước\2", str)
        str = re.sub("(^| )trc($| )", r"\1trước\2", str)
        str = re.sub("(^| )ae($| )", r"\1anh em\2", str)
        str = re.sub("(^| )đc($| )", r"\1được\2", str)
        str = re.sub("(^| )dc($| )", r"\1được\2", str)
        str = re.sub("(^| )dk($| )", r"\1được\2", str)
        str = re.sub("(^| )đk($| )", r"\1được\2", str)
        str = re.sub("(^| )k($| )", r"\1không\2", str)
        str = re.sub("(^| )ko($| )", r"\1không\2", str)
        str = re.sub("(^| )kg($| )", r"\1không\2", str)
        str = re.sub("(^| )kh($| )", r"\1không\2", str)
        str = re.sub("(^| )hk($| )", r"\1không\2", str)
        str = re.sub("(^| )khg($| )", r"\1không\2", str)
        str = re.sub("(^| )r($| )", r"\1rồi\2", str)
        str = re.sub("(^| )m($| )", r"\1mình\2", str)
        str = re.sub("(^| )mh($| )", r"\1mình\2", str)
        str = re.sub("(^| )mih($| )", r"\1mình\2", str)
        str = re.sub("(^| )mìh($| )", r"\1mình\2", str)
        str = re.sub("(^| )mk($| )", r"\1mình\2", str)
        str = re.sub("(^| )mik($| )", r"\1mình\2", str)
        str = re.sub("(^| )bh($| )", r"\1bao giờ\2", str)
        str = re.sub("(^| )h($| )", r"\1giờ\2", str)
        str = re.sub("(^| )jo($| )", r"\1giờ\2", str)
        str = re.sub("(^| )z($| )", r"\1vậy\2", str)
        str = re.sub("(^| )j($| )", r"\1gì\2", str)
        str = re.sub("(^| )cx($| )", r"\1cũng\2", str)
        str = re.sub("(^| )vs($| )", r"\1với\2", str)
        str = re.sub("(^| )ah($| )", r"\1à\2", str)
        str = re.sub("(^| )ak($| )", r"\1à\2", str)
        str = re.sub("(^| )ntn($| )", r"\1như thế nào\2", str)
        str = re.sub("(^| )lm($| )", r"\1làm\2", str)
        str = re.sub("(^| )trc($| )", r"\1trước\2", str)
        str = re.sub("(^| )t2($| )", r"\1thứ 2\2", str)
        str = re.sub("(^| )cn($| )", r"\1chủ nhật\2", str)
        str = re.sub("(^| )t3($| )", r"\1thứ 3\2", str)
        str = re.sub("(^| )t4($| )", r"\1thứ 4\2", str)
        str = re.sub("(^| )t5($| )", r"\1thứ 5\2", str)
        str = re.sub("(^| )t6($| )", r"\1thứ 6\2", str)
        str = re.sub("(^| )t7($| )", r"\1thứ 7\2", str)
        str = re.sub("(^| )mn($| )", r"\1mọi người\2", str)
        return str

    def doPreprocess(self, str):
        str = str.lower()
        str = self.replaceCompositUnicode(str)
        str = self.removeSpecialCharacter(str)
        str = self.replaceAcronym(str)
        # to lower case
        
        # number removing
        str = re.sub(r'\d+', '', str)
        # remove punctuation
#         str = str.translate(str.maketrans("","", string.punctuation))
        # remove white spaces
        str = str.strip()
        str = re.sub(' +', ' ', str)
        # # tokenize by pyvi
        str = ViTokenizer.tokenize(str)
        # # remove stopword
        # str = str.split()
        # str = [i for i in str if not i in self.stop_word]
        # str = ' '.join(str)
        return str

    def balance_classes(self,xs, ys):
        freqs = Counter(ys)
        max_allowable = freqs.most_common()[-1][1]
        num_added = {clss: 0 for clss in freqs.keys()}
        new_ys = []
        new_xs = []
        for i, y in enumerate(ys):
            if num_added[y] < max_allowable:
                new_ys.append(y)
                new_xs.append(xs[i])
                num_added[y] += 1
        return new_xs, new_ys


In [2]:
def readCSVData(fileName):
    star= []
    review = []
    p = Preprocess()
    with open(fileName) as csv_file:
        for row in csv_file:
            row = row.split('<fff>')
            star.append(row[0])
            review.append(p.doPreprocess(row[1]))
    review, star = p.balance_classes(review, star)
    return review, star

def readTXTData(fileName):
    star = []
    review = []
    p = Preprocess()
    with open(fileName, 'r') as fp:
        line = fp.readline()
        while line:
            star.append(line[0])
            review.append(p.doPreprocess(line[2:]))
            line = fp.readline()
            
    return review, star

In [3]:
x1_train, y1_train = readCSVData('data_final2.csv')
x_test, y_test = readTXTData('train.txt')

In [4]:
print(len(x_test))
x_train = x1_train + x_test[:150]
y_train = y1_train + y_test[:150]
x_test = x_test[151:500]
y_test = y_test[151:500]

# print(len(x_train))
from collections import Counter
print(Counter(y_train))

500
Counter({'5': 1033, '4': 987, '3': 976, '1': 968, '2': 961})


In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve


vectorizer = TfidfVectorizer(ngram_range=(1,2))
vectors = vectorizer.fit_transform(x_train)
print(vectors.toarra)
vectors1 = vectorizer.transform(x_test)
    #     return vectors

    # def fit(self):
        # vectors = self.tfidf()
classifier = LinearSVC()
        # train the classifier
classifier.fit(vectors, y_train)
        # return classifier
vectors1 = vectorizer.transform(x_test)
predict = classifier.predict(vectors1)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, predict)
# print(ac)
# print(confusion_matrix(y_test, predict))

  (0, 4069)	0.30623593629369744
  (0, 18294)	0.30623593629369744
  (0, 8006)	0.30623593629369744
  (0, 15084)	0.30623593629369744
  (0, 1778)	0.2539490171985226
  (0, 22931)	0.23619095626439665
  (0, 17546)	0.2921405703577373
  (0, 27074)	0.2539490171985226
  (0, 24343)	0.23858938648967223
  (0, 4067)	0.2921405703577373
  (0, 18286)	0.18118095206708013
  (0, 7996)	0.2077436664028333
  (0, 15081)	0.22449402055371212
  (0, 1708)	0.12698941509915115
  (0, 22918)	0.12127463851027563
  (0, 17507)	0.14866714129864375
  (0, 27053)	0.18214666554969683
  (1, 17779)	0.4701450104779424
  (1, 8391)	0.5102978150078954
  (1, 20068)	0.4701450104779424
  (1, 17772)	0.4018675868604548
  (1, 8381)	0.3688169205371595
  (2, 17558)	0.16960052109234577
  (2, 3116)	0.21572462555756025
  (2, 21736)	0.25751723009597577
  :	:
  (4922, 26196)	0.2666349640003292
  (4922, 7435)	0.21097954169615996
  (4922, 20359)	0.182176996024895
  (4922, 12005)	0.1847782714414848
  (4922, 26122)	0.1390710845479176
  (4922, 8738)

In [50]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix


nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])
nb.fit(x_train, y_train)

from sklearn.metrics import classification_report
y_pred = nb.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))

accuracy 0.6275071633237822
[[  3   5   3   2   5]
 [  0   4   1   1   2]
 [  0   1   7  13  19]
 [  0   1   6  56  24]
 [  0   2   4  41 149]]


In [45]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42, max_iter=5, tol=None)),
               ])
sgd.fit(x_train, y_train)


y_pred = sgd.predict(x_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))

accuracy 0.5616045845272206
[[  0   0   0   0  18]
 [  0   0   0   0   8]
 [  0   0   0   0  40]
 [  0   0   0   0  87]
 [  0   0   0   0 196]]


In [31]:
import numpy as np
from scipy.sparse import csr_matrix
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
aaaa = csr_matrix((data, (row, col)), shape=(3, 3))
print(aaaa)

  (0, 0)	0.1
  (0, 2)	0.2
  (1, 2)	0.3
  (2, 0)	0.4
  (2, 1)	0.5
  (2, 2)	0.6
